"""2023-06-20-one

Revision ID: 5c7accc8ade5
Revises: 
Create Date: 2023-06-20 15:56:39.346642

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.api_models import User

# revision identifiers, used by Alembic.
revision = '5c7accc8ade5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=40), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_category_title'), 'category', ['title'], unique=True)
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=35), nullable=False),
                    sa.Column('password', sa.Text(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('group', sqlalchemy_utils.types.choice.ChoiceType(User.GROUP_OF_USERS), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=250), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('author', sa.String(), nullable=False),
                    sa.Column('created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('published', sa.Boolean(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author'], ['user.username'], ),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_category_title'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
