"""2023-06-24-corected

Revision ID: 6d892a8064d5
Revises: 12b6323ddbde
Create Date: 2023-06-24 15:53:40.075274

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6d892a8064d5'
down_revision = '12b6323ddbde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
